# Generated by Django 3.0.3 on 2020-07-15 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Newspost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posttitle', models.CharField(max_length=500)),
                ('postdetail', models.CharField(max_length=5000)),
                ('postimage', models.FileField(null=True, upload_to='')),
                ('postdate', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emailid', models.CharField(max_length=40)),
                ('commentmsg', models.CharField(max_length=1000)),
                ('cdate', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('newspost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Newspost')),
            ],
        ),
    ]
