# Generated by Django 3.0.3 on 2020-07-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='postdetail',
            field=models.TextField(),
        ),
    ]
