# Generated by Django 3.0.3 on 2020-07-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200720_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=15)),
                ('emailid', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=300)),
                ('mdate', models.DateField()),
                ('isread', models.CharField(max_length=10)),
            ],
        ),
    ]
